config/routes.rb
Rails.application.routes.draw do
 # get 'uploads/index'

 # get 'uploads/new'

 # get 'uploads/create'

 # get 'uploads/destroy'

  get 'issues_watches/new'

  get 'issues_watches/create'

  get 'issues_watches/destroy'

  get 'issues_votes/new'

  get 'issues_votes/create'

  get 'issues_votes/destroy'

  resources :uploads, only: [:index, :new, :create, :destroy]
  resources :issue_lists
  resources :comments
  resources :issues
  resources :users
  resources :issues_votes
  resources :issues_watches
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'pages#index'
end

app/models/issue_list.rb
class IssueList < ApplicationRecord
  has_many :issues
end

app/controllers/issue_lists_controller.rb
class IssueListsController < ApplicationController
  before_action :set_issue_list, only: [:show, :edit, :update, :destroy]

  # GET /issue_lists
  # GET /issue_lists.json
  def index
    @issue_lists = IssueList.all
  end

  # GET /issue_lists/1
  # GET /issue_lists/1.json
  def show
  end

  # GET /issue_lists/new
  def new
    @issue_list = IssueList.new
  end

  # GET /issue_lists/1/edit
  def edit
  end

  # POST /issue_lists
  # POST /issue_lists.json
  def create
    @issue_list = IssueList.new(issue_list_params)

    respond_to do |format|
      if @issue_list.save
        format.html { redirect_to issues_path, notice: 'Issue list was successfully created.' }
        format.json { render :show, status: :created, location: @issue_list }
      else
        format.html { render :new }
        format.json { render json: @issue_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issue_lists/1
  # PATCH/PUT /issue_lists/1.json
  def update
    respond_to do |format|
      if @issue_list.update(issue_list_params)
        format.html { redirect_to @issue_list, notice: 'Issue list was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue_list }
      else
        format.html { render :edit }
        format.json { render json: @issue_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issue_lists/1
  # DELETE /issue_lists/1.json
  def destroy
    @issue_list.destroy
    respond_to do |format|
      format.html { redirect_to issue_lists_url, notice: 'Issue list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue_list
      @issue_list = IssueList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_list_params
      params.require(:issue_list).permit(:name)
    end
end

app/helpers/issue_lists_helper.rb
module IssueListsHelper
end

app/views/issue_lists/_form.html.erb
<%= form_for @issue_list, :html => {:class => "form-horizontal center"} do |form| %>
  <% if issue_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue_list.errors.count, "error") %> prohibited this issue_list from being saved:</h2>

      <ul>
      <% issue_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group col-md-8">
    <label class="required"><%= form.label :name %></label>
    <%= form.text_field :name, id: :issue_list_name, class: "form-control"%>
  </div>

  <div class="actions submit-button col-md-8">
    <%= form.submit "Create List", class: "btn btn-default btn-primary"%>
  </div>
<% end %>

app/views/issue_lists/edit.html.erb
<h1>Editing Issue List</h1>

<%= render 'form', issue_list: @issue_list %>

<%= link_to 'Show', @issue_list %> |
<%= link_to 'Back', issue_lists_path %>

app/views/issue_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issue Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issue_lists.each do |issue_list| %>
      <tr>
        <td><%= issue_list.name %></td>
        <td><%= link_to 'Show', issue_list %></td>
        <td><%= link_to 'Edit', edit_issue_list_path(issue_list) %></td>
        <td><%= link_to 'Destroy', issue_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue List', new_issue_list_path %>

app/views/issue_lists/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Issue</title>
  <%= stylesheet_link_tag "application" %>
</head>
<body>
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>New Issue List</h1>
  <br>
  <%= render 'form', issue_list: @issue_list %>

</div>

</body>

app/views/issue_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @issue_list.name %>
</p>

<%= link_to 'Edit', edit_issue_list_path(@issue_list) %> |
<%= link_to 'Back', issue_lists_path %>