config/routes.rb
Rails.application.routes.draw do
 # get 'uploads/index'

 # get 'uploads/new'

 # get 'uploads/create'

 # get 'uploads/destroy'

  get 'issues_watches/new'

  get 'issues_watches/create'

  get 'issues_watches/destroy'

  get 'issues_votes/new'

  get 'issues_votes/create'

  get 'issues_votes/destroy'

  resources :uploads, only: [:index, :new, :create, :destroy]
  resources :issue_lists
  resources :comments
  resources :issues
  resources :users
  resources :issues_votes
  resources :issues_watches
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'pages#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :issue
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments?issue_id=:issue_id
  # GET /comments?issue_id=:issue_id.json
  def index
    check_auth
    @comments = Comment.all
    #@comments = Issue.comments.all
  end

  # GET /comments/:id?issue_id=:issue_id
  # GET /comments/:id?issue_id=:issue_id.json
  def show
    check_auth
    @comments = Comment.all
    #@comments = Issue.comments.all
  end

  # GET /comments/new?issue_id=:issue_id
  def new
    check_auth
    @comment = Comment.new
    @issue = Issue.find(params[:issue_id])
  end

  # GET /comments/:id/edit?issue_id=:issue_id
  def edit
  end

  # POST /comments?issue_id=:issue_id
  # POST /comments?issue_id=:issue_id.json
  def create
    check_auth
    @comment = Comment.new(comment_params)
    @comment.user = current_user.username
    respond_to do |format|
      if @comment.save
        format.html { redirect_to  issue_path(@comment.issue_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/:id?issue_id=:issue_id
  # PATCH/PUT /comments/:id?issue_id=:issue_id.json
  def update
    check_auth
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to issue_path(@comment.issue_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/:id?issue_id=:issue_id
  # DELETE /comments/:id?issue_id=:issue_id.json
  def destroy
    check_auth
    @pathissue = issue_path(@comment.issue_id)
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @pathissue, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user, :comment, :issue_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, # url: {action="create" , params {:issue_id => @issue.id}},
:html => {:class => "form-horizontal center"} do |form| %>

    <% if comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if params[:action] == "new" %>
    <%= form.hidden_field :issue_id, { :value => @issue.id} %>
    <% end %>



    <div class="text_area form-group col-md-8">
      <%= form.label :comment %>
      <%= form.text_area :comment, id: :comment_comment, class: "form-control" %>
    </div>

    <% if params[:action] == "new" %>
    <div class="actions submit-button col-md-8">
      <%= form.submit "Comment", class: "btn btn-default btn-primary" %>
    </div>
    <%end%>
    
    <% if params[:action] == "edit" %>
    <div class="actions submit-button col-md-8">
      <%= form.submit "Save Changes", class: "btn btn-default btn-primary" %>
    </div>
    <%end%>
    
<% end %>

app/views/comments/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Editing Comment</title>
<%= stylesheet_link_tag "application" %>
</head>
<body>
  <p id="notice"><%= notice %></p>
  <div class="container">
    <h2>Editing Comment</h2>
    <br>
    <%= render 'form', comment: @comment %>
  </div>
  <div class="container">
    <%= link_to "Cancel" , issue_path(@comment.issue_id)%>
  </div>
</body>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comment</th>
      <th>Issue</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.issue_id %></td>
        <td><%= comment.created_at.strftime("%d-%m-%Y %R") %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>New Comment</title>
<%= stylesheet_link_tag "application" %>
</head>
<body>
  <p id="notice"><%= notice %></p>
  <div class="container">
    <h2>New Comment</h2>
    <br>
    <%= render 'form', comment: @comment %>
  </div>
</body>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @comment.issue_id %>
</p>

<p>
  <strong>Created:</strong>
  <%= @comment.created_at.strftime("%d-%m-%Y %R") %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>