config/routes.rb
Rails.application.routes.draw do
 # get 'uploads/index'

 # get 'uploads/new'

 # get 'uploads/create'

 # get 'uploads/destroy'

  get 'issues_watches/new'

  get 'issues_watches/create'

  get 'issues_watches/destroy'

  get 'issues_votes/new'

  get 'issues_votes/create'

  get 'issues_votes/destroy'

  resources :uploads, only: [:index, :new, :create, :destroy]
  resources :issue_lists
  resources :comments
  resources :issues
  resources :users
  resources :issues_votes
  resources :issues_watches
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'pages#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
    validates :title, presence: true
    validates :kind, presence: true
    validates :priority, presence: true
    VALID_KINDS = %w( bug enhancement proposal task )
    validates_inclusion_of :kind, :in => VALID_KINDS
    VALID_PRIORITIES = %w( trivial minor major critical blocker )
    validates_inclusion_of :priority, :in => VALID_PRIORITIES
    belongs_to :issue_list
    has_many :comments, dependent: :destroy
    has_many :uploads, dependent: :destroy
    
    accepts_nested_attributes_for :comments
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
    before_action :set_issue, only: [:show, :edit, :update, :destroy]

    # GET /issues
    # GET /issues.json
    def index
        check_auth
        @issues = Issue.all
        @users = User.all
        @issues_lists = IssueList.all
        @param_issue=params[:issue_list]
      if @param_issue
          @issue_list_id = IssueList.where(:name => @param_issue).first.id
          @issues = Issue.where(:issue_list_id => @issue_list_id)
      end
    end

    # GET /issues/1
    # GET /issues/1.json
    def show
        check_auth
        @uploads=Upload.where(:issues_id => @issue.id)
        @users=User.all
    end

    # GET /issues/new
    def new
        check_auth
        @issue = Issue.new
    end

    # GET /issues/1/edit
    def edit
        check_auth
    end

    # POST /issues
    # POST /issues.json
    def create
        check_auth
        @issue = Issue.new(issue_params)
        @issue.status = "new"
        @issue.votes = 0

        respond_to do |format|
            if @issue.save
                format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
                format.json { render :show, status: :created, location: @issue }
                else
                format.html { render :new }
                format.json { render json: @issue.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /issues/1
    # PATCH/PUT /issues/1.json
    def update
        check_auth
        respond_to do |format|
            if @issue.update(issue_params)
                format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
                format.json { render :show, status: :ok, location: @issue }
                else
                format.html { render :edit }
                format.json { render json: @issue.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /issues/1
    # DELETE /issues/1.json
    def destroy
        check_auth
        @issue.destroy
        respond_to do |format|
            format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
        @issue = Issue.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
        params.require(:issue).permit(:title, :kind, :priority, :status, :votes, :assignee, :created, :updated, :description, :comments, :issue_list_id, :issue_creator )
    end

    # GET /issues/1/edit
    def edit
        check_auth
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for @issue, :html => {:class => "form-horizontal center"} do |form| %>
    <% if issue.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

          <ul>
            <% issue.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group col-md-8">
      <label class="required">Title</label>
      <%= form.text_field :title, id: :issue_title, class: "form-control" %>
    </div>

    <div class="field form-group col-md-8">
      <label class="required">Kind</label>
      <%= form.select :kind, [['Bug', 'bug'], ['Enhancement', 'enhancement'], ['Proposal', 'proposal'], ['Task', 'task']], {}, class: "form-control" %>
      <% form.submit %>
    </div>

    <div class="field form-group col-md-8">
      <label class="required">Priority</label>
      <%= form.select :priority, [['Trivial', 'trivial'], ['Minor', 'minor'], ['Major', 'major'], ['Critical', 'critical'], ['Blocker', 'blocker']], {}, class: "form-control" %>
      <% form.submit %>
    </div>

    <% if params[:action] == "edit" %>
        <div class="field form-group col-md-8">
          <label>Status</label>
          <%= form.select :status, [['New', 'new'], ['Resolved', 'resolved'], ['WontFix', 'wontfix']], {}, class: "form-control" %>
          <% form.submit %>
        </div>
    <% end %>

    <div class="field form-group col-md-8">
      <%= form.label :assignee %>
      <!-- f.select :category, Category.all, :prompt => "Select One"
      :category, Category.all.map{|c| [c.name, c.id]}, :prompt => "Select One"
      form.text_field :assignee, id: :issue_assignee, class: "form-control"-->
      <%= form.select :assignee, User.all.map {|c| [c.username, c.username]}, {}, class: "form-control", :prompt => "Select One" %>

    </div>

    <div class="field form-group col-md-8">
      <%= form.label :issue_list_id %>
      <!-- f.select :category, Category.all, :prompt => "Select One"
      :category, Category.all.map{|c| [c.name, c.id]}, :prompt => "Select One"
      form.text_field :assignee, id: :issue_assignee, class: "form-control"-->
      <%= form.select :issue_list_id, IssueList.all.map {|c| [c.name, c.id]}, {}, class: "form-control", :prompt => "Select One" %>

    </div>

    <div class="text_area form-group col-md-8">
      <%= form.label :description %>
      <%= form.text_area :description, id: :issue_description, class: "form-control" %>
    </div>
    <% if params[:action] == "new" %>
        <%= form.hidden_field :issue_creator, { :value => current_user.username} %>
    <% end %>

    <% if params[:action] == "new" %>
        <div class="actions submit-button col-md-8">
          <%= form.submit "Create issue", class: "btn btn-default btn-primary" %>
          <p><a href="/" data-confirm="Chages do not saved. Go back?">Cancel</a></p>
        </div>
    <% end %>

    <% if params[:action] == "edit" %>
        <div class="actions submit-button col-md-8">
          <%= form.submit "Save changes", class: "btn btn-default btn-primary" %>
          <p id="cancel"><a href="." data-confirm="Chages do not saved. Go back?">Cancel</a></p>
        </div>
    <% end %>


<% end %>

app/views/issues/edit.html.erb
<html>
<head>
  <title>Edit</title>
  <%= stylesheet_link_tag "application" %>
</head>
<body>
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Edit issue</h1>

  <%= render 'form', issue: @issue %>
  <!--<%= form_for @issue, :html => {:class => "form-horizontal center"} do |form| %>
<div class="field form-group col-md-8">
    <label class="required">Status</label>
    <%= form.select :status, [['New', 'new'], ['Resolved', 'resolved'], ['WontFix', 'wontfix']], {}, class: "form-control" %>
    <% form.submit %>
</div>
<% end %>-->

</div>
</body>

app/views/issues/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Index</title>

  <%= stylesheet_link_tag "application" %>
</head>
<body>
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Issues</h1>

  <div id="issues-toolbar">
    <div class="filter-container">
      <p id="filter-label">FILTER BY:</p>
      <table class="filters-table">
      <tr class="filter-status">
        <td id="all" aria-pressed="true">
          <a href="/issues">All</a>
        </td>
        <% @issues_lists.each do |issue_list| %>
        <td>
          <a href=/issues?issue_list=<%= issue_list.name %>><%= issue_list.name%></a>
        </td>
            <% end %>

      </tr>
      </table>
    </div>
  </div>
  <div id="issues">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Title</th>
        <th>T</th>
        <th>P</th>
        <th>Status</th>
        <th>Votes</th>
        <th>Assignee</th>
        <th>Created</th>
        <th>Updated</th>
      </tr>
      </thead>

      <tbody>
      <% @issues.each do |issue| %>
          <tr>
            <td>
              <a href=/issues/<%= issue.id %>>
                #<%= issue.id %>: <%= issue.title %>
              </a>
            </td>
            <td><%= issue.kind %></td>
            <td><%= issue.priority %></td>
            <td><%= issue.status %></td>
            <td><%= IssuesVote.where(issue_id: issue.id).count %></td>
            <% if issue.assignee != "" %>
                <td class><a href=/users/<%= issue.assignee %>>
                  <%= issue.assignee %></a></td>
            <% else %>
                <td><%= issue.assignee %></td>
            <% end %>
            <td><%= time_ago_in_words(issue.created_at.strftime("%d-%m-%Y %R")) %> ago</td>
            <td><%= time_ago_in_words(issue.updated_at.strftime("%d-%m-%Y %R")) %> ago</td>
            <!--<td><%= link_to '', edit_issue_path(issue) %></td> -->
            <!--<td><%= link_to 'Destroy', issue, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</body>

app/views/issues/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>New Issue</title>
<%= stylesheet_link_tag "application" %>
</head>
<body>
  <p id="notice"><%= notice %></p>
  <div class="container">
    <h1>New Issue</h1>
    <br>
    <%= render 'form', issue: @issue %>

  </div>

</body>

app/views/issues/show.html.erb
<html>
<head>
  <title>Issue #<%= @issue.id %>: <%= @issue.title %></title>
  <!-- Latest compiled and minified CSS -->
  <%= stylesheet_link_tag "application" %>
</head>
<body>
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="issue-header">
    <h2>Issue #<%= @issue.id %>: <%= @issue.title %>  <%= @issue.status %></h2>
  </div>
  <div class="issue-info">
    <div class="issue-info-left">
      <div id="issue-main-content">
        <p><%= image_tag current_user.image_url %>
          <%= link_to User.where(username: @issue.issue_creator).first.full_name, user_path(@issue.issue_creator) %>
          created
          an issue <%= @issue.created_at.strftime("%d-%m-%Y") %></p>
        <p>
          <strong>Description:</strong> <%= @issue.description %>
        </p>
        <p>
          <% @uploads.each do |upload| %>
            <td>
              <a href=<%= upload.attachment_url %>><%= upload.name%></a>
            </td>
        <% end %>
        </p>
        <a href=<%= edit_issue_path(@issue.id) %>><button type="button" class="btn btn-default">Edit</button></a>
        <a href=/uploads/new?issue_id=<%= @issue.id %>><button type="button" class="btn btn-default">Upload</button></a>

      </div>
    </div>
    <div class="issue-attrs">
      <p>
        <strong>Assignee: </strong>
        <%= link_to @issue.assignee, user_path(@issue.assignee) %>
      </p>
      <p>
        <strong>Kind:</strong> <%= @issue.kind %>
      </p>

      <p>
        <strong>Priority:</strong> <%= @issue.priority %>
      </p>

      <p>
        <strong>Status:</strong> <%= @issue.status %>
      </p>

      <p>
        <strong>Votes:</strong> <%= IssuesVote.where(issue_id: @issue.id).count %>
        <% if IssuesVote.where(issue_id: @issue.id).count == 0 %>
          <%= link_to "Vote for this issue",
          new_issues_vote_path(:issue_id => @issue.id, :username => @issue.assignee) %>
        <% else %>
          <%= link_to "Remove vote",
          issues_vote_path(:issue_id => @issue.id, :username => @issue.assignee),
          method: :delete %>
        <% end %>
      </p>

      <p>
        <strong>Watchers:</strong> <%= IssuesWatch.where(issue_id: @issue.id).count %>
        <% if IssuesWatch.where(issue_id: @issue.id).count == 0 %>
          <%= link_to "Watch this issue",
          new_issues_watch_path(:issue_id => @issue.id, :username => @issue.assignee) %>
        <% else %>
          <%= link_to "Stop watching",
          issues_watch_path(:issue_id => @issue.id, :username => @issue.assignee),
          method: :delete %>
        <% end %>
      </p>


    </div>
    <div class="issues-footer">
      <h3>Comments (<%= @issue.comments.count %>)</h3>
      <% if not @issue.comments.empty? %>
          <% @issue.comments.each do |comment| %>
              <p><%= image_tag current_user.image_url %>
                <%= link_to User.where(username: @issue.issue_creator).first.full_name, user_path(@issue.issue_creator) %>
                (<%= time_ago_in_words(comment.created_at.strftime("%d-%m-%Y %R")) %> ago):    <%= comment.comment %>
              </p>
              <p><%= link_to 'Edit', edit_comment_path(:id => comment.id, :issue_id => @issue.id) %>
                | <%= link_to 'Delete', comment, method: :delete, data: {confirm: 'Are you sure?'} %></p>
          <% end %>
      <% end %>

    </div>
    <div id="issue-add-comment">
      <a href= <%=new_comment_path(:issue_id => @issue.id) %>><button type="button" class="btn btn-default">Add comment</button></a>
    </div>
  </div>


</div>
</body>