config/routes.rb
Rails.application.routes.draw do
 # get 'uploads/index'

 # get 'uploads/new'

 # get 'uploads/create'

 # get 'uploads/destroy'

  get 'issues_watches/new'

  get 'issues_watches/create'

  get 'issues_watches/destroy'

  get 'issues_votes/new'

  get 'issues_votes/create'

  get 'issues_votes/destroy'

  resources :uploads, only: [:index, :new, :create, :destroy]
  resources :issue_lists
  resources :comments
  resources :issues
  resources :users
  resources :issues_votes
  resources :issues_watches
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true

    def self.from_omniauth(auth_hash)
        user = where(username: auth_hash.info.nickname).first_or_create
        user.update(
            image_url: auth_hash.info.image,
            full_name: auth_hash.info.name,
        )
        user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :username, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, id: :user_full_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Index</title>

<%= stylesheet_link_tag "application" %>
</head>
<body>
    <p id="notice"><%= notice %></p>
    <div class="container">
    <h1>Users</h1>

    <table>
    <thead>
        <tr>
        <th>Full name</th>
        <th>Username</th>
        <th>Email</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.full_name %></td>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
    <br>

    </div>
</body>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<html>
<head>
<title>Account</title>
<!-- Latest compiled and minified CSS -->
<%= stylesheet_link_tag "application" %>
<style type="text/css">
    h4 {
        font-family: sans-serif;
    }
    
    th {
        margin-left:30px;
        color: #BEBEBE;
        font-family: sans-serif;
    }
    
</style>
</head>
<body>
    <div class="container">
        <p id="notice"><%= notice %></p>
        
        <div class="account settings">
        
        <h3>Account</h3>
        
        <table>
        <tr>
            <th><h5>Avatar</h5></th>
            <td><%= image_tag @user.image_url, alt: @user.username, :size => "100x100" %></td>
        </tr>
        <tr>
            <th><h5>Full name</h5></th>
            <td><h5><%= @user.full_name %></h5></td>
        </tr>
        <tr>
            <th><h5>Username</h5></th>
            <td><h5><%= @user.username %></h5></td>
        </tr>
        
        </table>
      </div>  
  </div>
</body>